import { App, Modal, MarkdownRenderer, Notice } from 'obsidian';
import type ClarityPlugin from '../../main';

export interface ReframeResult {
	content: string;
	provider: 'gemini' | 'claude-sonnet' | 'claude-haiku' | 'pattern';
	sources: string[];
	isPatternMatch?: boolean;
	patternScore?: number;
	patternName?: string;
}

export class ResultModal extends Modal {
	plugin: ClarityPlugin;
	private result: ReframeResult;
	private onSave: (wasHelpful: boolean) => void;
	private onMoodAfter?: (mood: number) => void;
	private wasHelpful: boolean = true; // Default to helpful

	constructor(
		app: App,
		plugin: ClarityPlugin,
		result: ReframeResult,
		onSave: (wasHelpful: boolean) => void,
		onMoodAfter?: (mood: number) => void
	) {
		super(app);
		this.plugin = plugin;
		this.result = result;
		this.onSave = onSave;
		this.onMoodAfter = onMoodAfter;
	}

	async onOpen() {
		const { contentEl } = this;
		contentEl.empty();
		contentEl.addClass('clarity-result-modal');

		// Title
		contentEl.createEl('h2', { text: '🧭 Clarity Reframe' });

		// Pattern match indicator
		if (this.result.isPatternMatch) {
			const matchIndicator = contentEl.createDiv({ cls: 'clarity-pattern-indicator' });
			const scorePercent = Math.round((this.result.patternScore || 0) * 100);
			matchIndicator.createEl('span', {
				text: `✨ Pattern matched: ${this.result.patternName} (${scorePercent}%)`,
				cls: 'clarity-pattern-badge'
			});
		}

		// Reframe content (rendered as markdown)
		const contentContainer = contentEl.createDiv({ cls: 'clarity-reframe-content' });
		await MarkdownRenderer.render(
			this.app,
			this.result.content,
			contentContainer,
			'',
			this.plugin
		);

		// Sources
		if (this.result.sources.length > 0) {
			const sourcesContainer = contentEl.createDiv({ cls: 'clarity-sources' });
			sourcesContainer.createEl('h4', { text: 'Sources:' });
			const sourcesList = sourcesContainer.createEl('ul');
			this.result.sources.forEach(source => {
				const li = sourcesList.createEl('li');
				li.createEl('a', {
					text: source,
					href: source,
					cls: 'internal-link'
				});
			});
		}

		// Provider info
		const providerInfo = contentEl.createDiv({ cls: 'clarity-provider-info' });
		providerInfo.createEl('small', {
			text: `Generated by ${this.getProviderName(this.result.provider)}`
		});

		// Effectiveness rating
		contentEl.createEl('label', { text: 'Was this reframe helpful?' });
		const effectivenessContainer = contentEl.createDiv({ cls: 'clarity-effectiveness-container' });

		const helpedBtn = effectivenessContainer.createEl('button', {
			text: '👍 Helped',
			cls: 'clarity-effectiveness-btn active'
		});
		const didntHelpBtn = effectivenessContainer.createEl('button', {
			text: "👎 Didn't Help",
			cls: 'clarity-effectiveness-btn'
		});

		helpedBtn.addEventListener('click', () => {
			this.wasHelpful = true;
			helpedBtn.classList.add('active');
			didntHelpBtn.classList.remove('active');
		});

		didntHelpBtn.addEventListener('click', () => {
			this.wasHelpful = false;
			didntHelpBtn.classList.add('active');
			helpedBtn.classList.remove('active');
		});

		// Mood after (if enabled)
		if (this.plugin.settings.includeMoodRating && this.onMoodAfter) {
			contentEl.createEl('label', { text: 'Mood after reframe (1-10)' });
			const moodContainer = contentEl.createDiv({ cls: 'clarity-mood-container' });

			for (let i = 1; i <= 10; i++) {
				const btn = moodContainer.createEl('button', {
					text: String(i),
					cls: 'clarity-mood-btn'
				});
				btn.addEventListener('click', () => {
					this.onMoodAfter!(i);
					moodContainer.querySelectorAll('.clarity-mood-btn').forEach((b, idx) => {
						b.classList.toggle('active', idx + 1 === i);
					});
				});
			}
		}

		// Buttons
		const buttonContainer = contentEl.createDiv({ cls: 'clarity-button-container' });

		const copyBtn = buttonContainer.createEl('button', { text: 'Copy to Clipboard' });
		copyBtn.addEventListener('click', async () => {
			await navigator.clipboard.writeText(this.result.content);
			new Notice('Copied to clipboard');
		});

		const doneBtn = buttonContainer.createEl('button', {
			text: 'Done',
			cls: 'mod-cta'
		});
		doneBtn.addEventListener('click', () => {
			this.onSave(this.wasHelpful);
			if (!this.wasHelpful) {
				new Notice('Archived as unhelpful');
			}
			this.close();
		});
	}

	private getProviderName(provider: string): string {
		switch (provider) {
			case 'gemini': return 'Gemini';
			case 'claude-sonnet': return 'Claude Sonnet 4.5';
			case 'claude-haiku': return 'Claude Haiku';
			case 'pattern': return 'Cached Pattern';
			default: return provider;
		}
	}

	onClose() {
		const { contentEl } = this;
		contentEl.empty();
	}
}
