import { App, Modal, MarkdownRenderer, Notice } from 'obsidian';
import type ClarityPlugin from '../../main';

export interface ReframeResult {
	content: string;
	provider: 'gemini' | 'claude-sonnet' | 'claude-haiku';
	sources: string[];
}

export class ResultModal extends Modal {
	plugin: ClarityPlugin;
	private result: ReframeResult;
	private onSave: () => void;
	private onMoodAfter?: (mood: number) => void;

	constructor(
		app: App, 
		plugin: ClarityPlugin, 
		result: ReframeResult,
		onSave: () => void,
		onMoodAfter?: (mood: number) => void
	) {
		super(app);
		this.plugin = plugin;
		this.result = result;
		this.onSave = onSave;
		this.onMoodAfter = onMoodAfter;
	}

	async onOpen() {
		const { contentEl } = this;
		contentEl.empty();
		contentEl.addClass('clarity-result-modal');

		// Title
		contentEl.createEl('h2', { text: '🧭 Clarity Reframe' });

		// Reframe content (rendered as markdown)
		const contentContainer = contentEl.createDiv({ cls: 'clarity-reframe-content' });
		await MarkdownRenderer.render(
			this.app,
			this.result.content,
			contentContainer,
			'',
			this.plugin
		);

		// Sources
		if (this.result.sources.length > 0) {
			const sourcesContainer = contentEl.createDiv({ cls: 'clarity-sources' });
			sourcesContainer.createEl('h4', { text: 'Sources:' });
			const sourcesList = sourcesContainer.createEl('ul');
			this.result.sources.forEach(source => {
				const li = sourcesList.createEl('li');
				li.createEl('a', {
					text: source,
					href: source,
					cls: 'internal-link'
				});
			});
		}

		// Provider info
		const providerInfo = contentEl.createDiv({ cls: 'clarity-provider-info' });
		providerInfo.createEl('small', { 
			text: `Generated by ${this.getProviderName(this.result.provider)}` 
		});

		// Mood after (if enabled)
		if (this.plugin.settings.includeMoodRating && this.onMoodAfter) {
			contentEl.createEl('label', { text: 'Mood after reframe (1-10)' });
			const moodContainer = contentEl.createDiv({ cls: 'clarity-mood-container' });
			
			for (let i = 1; i <= 10; i++) {
				const btn = moodContainer.createEl('button', {
					text: String(i),
					cls: 'clarity-mood-btn'
				});
				btn.addEventListener('click', () => {
					this.onMoodAfter!(i);
					moodContainer.querySelectorAll('.clarity-mood-btn').forEach((b, idx) => {
						b.classList.toggle('active', idx + 1 === i);
					});
				});
			}
		}

		// Buttons
		const buttonContainer = contentEl.createDiv({ cls: 'clarity-button-container' });

		const copyBtn = buttonContainer.createEl('button', { text: 'Copy to Clipboard' });
		copyBtn.addEventListener('click', async () => {
			await navigator.clipboard.writeText(this.result.content);
			new Notice('Copied to clipboard');
		});

		if (this.plugin.settings.autoSaveToLog) {
			const savedNote = buttonContainer.createEl('span', { 
				text: '✓ Saved to log',
				cls: 'clarity-saved-note'
			});
		} else {
			const saveBtn = buttonContainer.createEl('button', { text: 'Save to Log' });
			saveBtn.addEventListener('click', () => {
				this.onSave();
				new Notice('Saved to log');
				saveBtn.setText('✓ Saved');
				saveBtn.disabled = true;
			});
		}

		const closeBtn = buttonContainer.createEl('button', { 
			text: 'Close',
			cls: 'mod-cta'
		});
		closeBtn.addEventListener('click', () => this.close());
	}

	private getProviderName(provider: string): string {
		switch (provider) {
			case 'gemini': return 'Gemini';
			case 'claude-sonnet': return 'Claude Sonnet 4.5';
			case 'claude-haiku': return 'Claude Haiku';
			default: return provider;
		}
	}

	onClose() {
		const { contentEl } = this;
		contentEl.empty();
	}
}
